name: Get security advisories report
on:
  pull_request:
    branches:
      - 'dependabot/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Run OWASP Dependency Check
      run: ./gradlew dependencyCheckAnalyze --no-daemon

    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v2
      with:
        name: Dependency-Check-Report
        path: build/dependency-check
