name: Get security advisories report
on:
  pull_request:
    branches:
      'depepndabot/**'
jobs:
  get-security-advisories-report:
    runs-on: ubuntu-latest
    steps:
      - uses: github/actions/security-advisories-report@v1
      - name: Print vulnerabilities
        run: |
          for advisory in advisories:
            if advisory.severity == "critical":
              echo "Vulnerability name: ${advisory.name}"
              echo "Vulnerability severity: ${advisory.severity}"
              echo "Vulnerability description: ${advisory.description}"
              echo "Vulnerability fix instructions: ${advisory.fix_instructions}"
