name: 'Check for Vulnerabilities'

on:
  pull_request:
    branches:
      'dependabot/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # X.X.X - Latest version available at: https://github.com/kunalnagarco/action-cve/releases
      - uses: kunalnagarco/action-cve@v1.8.1
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          slack_webhook: ${{ secrets.DEPENDABOT_SLACK_SECRET }}
