name: Get security dashboard metrics

on:
  pull_request:
    branches:
      - 'dependabot/**'
      
jobs:
  get-security-dashboard-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: github/actions/get-security-dashboard-metrics@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          vulns = get_security_dashboard_metrics()
          table = []
          for vulnerability in vulns:
            table.append({
              "name": vulnerability.name,
              "severity": vulnerability.severity,
              "description": vulnerability.description,
          })

          attachments = [
          {
            "color": "danger",
            "fields": [
              {
                "title": "Vulnerabilidades graves",
                "value": table[0]
              }
            ]
          },
          {
            "color": "warning",
            "fields": [
              {
                "title": "Vulnerabilidades médias",
                "value": table[1]
              }
            ]
          },
          {
            "color": "good",
            "fields": [
              {
                "title": "Vulnerabilidades baixas",
                "value": table[2]
              }
            ]
          }
          ]

          slack:
          channel: '#segurança'
          icon_emoji: ':lock:'
          attachments: attachments
          slack_bot_token: ${{ secrets.DEPENDABOT_SLACK_SECRET }}
