name: Dependabot-Slack

on:
  pull_request:
    branches:
      - 'dependabot/**'

jobs:
  notify_slack_on_pull_request:
    runs-on: ubuntu-20.04s
    name: Sends a message to Slack when a pull request is opened
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.DEPENDABOT_SLACK_SECRET }}
          slack-channel: dependabot-alerts
          slack-text: New Dependabot PR ${{ github.event.pull_request.html_url }}
