name: Dependabot Sync
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  check_findings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check findings
        uses: dependabot/dependency-review-action@v2
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          dependency-review-url: https://api.github.com/repos/${{ github.repository }}/commits/${{ github.head_commit.id }}/dependency-review

      - name: Create pull request
        if:
          steps.check_findings.outputs.findings.length > 0 && steps.check_findings.outputs.findings.some(finding => finding.severity === 'high' || finding.severity === 'medium')
        uses: actions/github-script@v3
        with:
          script: |
            import json

            findings = json.loads(github.event.inputs.check_findings.outputs.findings)

            for finding in findings:
              if finding.severity === 'high' || finding.severity === 'medium':
                title = finding['package']['name'] + ' ' + finding['vulnerability']['name']
                body = finding['vulnerability']['description']

                octokit.post(
                  'https://api.github.com/repos/{}/{}/pulls'.format(github.repository, github.head_ref),
                  headers={'Authorization': 'bearer {}'.format(github.token)},
                  data={
                    'title': title,
                    'body': body,
                    'head': github.head_sha,
                    'base': github.base_ref,
                  }
                )
